name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group and ACR
        run: |
          az group create --name MyResourceGroup4 --location westus2  # Changed location to West US 2
          az acr create --name oztestaks4 --resource-group MyResourceGroup4 --sku Basic --admin-enabled false

      - name: Create AKS Cluster in Private Network
        run: |
          az aks create --resource-group MyResourceGroup4 --name MythirdCluster --node-count 2 --generate-ssh-keys --attach-acr oztestaks3 --enable-private-cluster
          az aks get-credentials --resource-group MyResourceGroup4 --name MythirdCluster --overwrite-existing
