name: Deploy NGINX Ingress Controller to AKS

on:
  push:
    branches:
      - main  # Adjust this as necessary for your workflow triggers

jobs:
  deploy-traefik:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group MyResourceGroup --name MyFirstCluster --overwrite-existing

      - name: Install NGINX Ingress Controller
        run: |
          kubectl create namespace ingress-nginx
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml
