name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Create ACR
      run: |
        az acr create --name oztestaks2 --resource-group MyResourceGroup2 --sku Basic --admin-enabled false

    - name: Create AKS Cluster in Private Network
      run: |
        az group create --name MyResourceGroup2 --location eastus
        az aks create --resource-group MyResourceGroup2 --name MyFirstCluster --node-count 2 --generate-ssh-keys --attach-acr oztestaks2 --enable-private-cluster
        az aks get-credentials --resource-group MyResourceGroup2 --name MyFirstCluster --overwrite-existing

    - name: Install Ingress Controller
      run: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.41.0/deploy/static/provider/cloud/deploy.yaml
