name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create ACR
        run: |
          az acr create --name oztestaks3 --resource-group MyResourceGroup3 --sku Basic --admin-enabled false

      - name: Create Resource Group
        run: |
          az group create --name MyResourceGroup3 --location eastus

      - name: Create AKS Cluster with Public Access
        run: |
          az aks create --resource-group MyResourceGroup3 --name MyThirdCluster --node-count 2 --generate-ssh-keys --attach-acr oztestaks3
          az aks get-credentials --resource-group MyResourceGroup3 --name MyThirdCluster --overwrite-existing

      - name: Install Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.41.0/deploy/static/provider/cloud/deploy.yaml
